language: swift
xcode_workspace: CareFree.xcworkspace
xcode_scheme: CareFree
osx_image: xcode11.3
podfile: path/to/Podfile
branches:
  only:
    - master
    - /release*/
cache:
  - bundler
  - cocoapods
before_install:
  - bundle install
  - export CI=1
  - pod install || pod install --repo-update
script:
  - bundle update fastlane
  - fastlane beta
