language: swift
xcode_workspace: CareFree.xcworkspace
xcode_scheme: CareFree
osx_image: xcode11.3
podfile: path/to/Podfile
branches:
  only:
  - master
  - "/release*/"
cache:
- cocoapods
before_install:
- bundle install
- pod install || pod install --repo-update
script:
- fastlane ci
env:
  global:
  - secure: SaQsfG7iUikmTekgyfAVNoYD/nO2lHBjeP+/T9UuejTVHJMJzuwQfjei5Qw6K+QBUaALJfw0kIE0TYZaQEVrC+spKV/yny6MiOgTtRTxMQwjmHs28uHf1Na2a1wZQ6RyrTKvsgIwjrf2WB/eqjkG6OiNVJkQLA6kaRKvpLsi/wa/n/wWqLIONsFUvYzVX7NhhO2QI+fgvjpHCnwl67TojhB4xRjfLNO2HZWPvhenWPYmKkagd+Ef9pcwyBn8SMRCQml8TGRaUV0iNScm84qfpu6c1+cEjnTXlERaksvgBVhBPo8WOzhd+QBu/77bfnCAyGf+wsDRru2uums7SLuRiBijjn/dMUgCnLjj3s6d3od4LafPFhEuFZ2fnz6ipg+OuqHLLgvB7dMpOEn6ld5yayr4oV3KS6e4aJ4dEaTYO48htoEToMt9Ye0hwaekVLux25u/bSLcg1LOM4SBROwamqNwRXDn3TFmU7N0R9M4LYlkZl2UzLhZNwAcqkyMhTE5mVxjle6yPMsCDJsWNusb+V0NJZPaPhJ3OOTps9ttMmgTCPVcskSsb0pSkplPvt46qi8wU2ADCMyvOXMXC7V/XlPLUqaK9EF53mI57F2PUcQaymJkvlCGR5kpygmGwF4lc+8BuItgTisc+Pzjk7VQ7H8ZAqWxc0VDGuNxgC1VJR8=
  - secure: G+fP2WDg6nuXeHwsRLgKGJUyZWLyEYxUp0rCmqCHEM61b3pTmGP7EJ3p/x5h9HrSNcihhT78cr53bYNy1Lcep3SQ5RqM9tVtbCtkCHM3P6sHVRuaM8+F+kludNG56ZmOh5fxoqjyAmOPnOHa8iS45d9apvbWHzKcocLBKvcKivX/CCpih0wjIz2ogrjcKDVIiz65humbcc4LVIpMt2U65FVSIRiB4TftXAnB7Qut7uoltG+gNbhD7nDszJNN++t9OOLbh4jz8Gbr0o/viBLSfZS3IymuvFkJevY89p643lxgYJFGxhRf3bOy1lUt8rIEawPHfY/qa7vCmGir71FeyQhtgJE2TVNPJcPd7XtwmrxMfnVNIi6vTapNt3OU3n1wXM8JH3IUE2+irSdkG49cEIv2EsCPtPJh5WRsHrPJpYh0fZwuWusFsqi8CSSYed6kRKPqjawwpBIOqNtWyBS4k0LRcOfRPAb1p6RAmsjPgZvN5RZ1BVgjd4YOCK/JM62zVhiu5mqKTJOpohMkO0Jdl17cJ4QWNgNoa3DMqUCJfAdiK1ywLQVtkPXcMytQrKpd3+1tso8vfCFcbAqn0csJn7n/5JoGbJ1p40Y9/DRvw57fHawAga0qmbVchqYMulHueYqHvVHGwK8B25u8KwyPEKykzxJl9K5i85qaWtFQhDE=
